// Card/character definitions. Each troop has stats balanced relative to its elixir cost.
const CARD_TYPES = {
  knight: {
    name: 'Knight',
    icon: '⚔️',
    cost: 3,
    hp: 600,
    damage: 80,
    speed: 40,
    range: 24,
    attackInterval: 1.1,
    targets: 'ground',
    splash: false,
  },
  archer: {
    name: 'Archer',
    icon: '🏹',
    cost: 3,
    hp: 250,
    damage: 60,
    speed: 45,
    range: 120,
    attackInterval: 1.0,
    targets: 'any',
    splash: false,
  },
  giant: {
    name: 'Giant',
    icon: '🗿',
    cost: 5,
    hp: 1500,
    damage: 110,
    speed: 25,
    range: 24,
    attackInterval: 1.4,
    targets: 'buildings',
    splash: false,
  },
  goblin: {
    name: 'Goblin',
    icon: '👺',
    cost: 2,
    hp: 150,
    damage: 50,
    speed: 60,
    range: 22,
    attackInterval: 0.7,
    targets: 'ground',
    splash: false,
  },
  wizard: {
    name: 'Wizard',
    icon: '🧙',
    cost: 4,
    hp: 340,
    damage: 90,
    speed: 38,
    range: 100,
    attackInterval: 1.3,
    targets: 'any',
    splash: true,
  },
  dragon: {
    name: 'Baby Dragon',
    icon: '🐉',
    cost: 4,
    hp: 450,
    damage: 80,
    speed: 50,
    range: 90,
    attackInterval: 1.2,
    targets: 'any',
    splash: true,
    flying: true,
  },
  golem: {
    name: 'Golem',
    icon: '🪨',
    cost: 7,
    hp: 2600,
    damage: 130,
    speed: 18,
    range: 24,
    attackInterval: 1.6,
    targets: 'buildings',
    splash: false,
  },
  musketeer: {
    name: 'Musketeer',
    icon: '🔫',
    cost: 4,
    hp: 300,
    damage: 100,
    speed: 40,
    range: 130,
    attackInterval: 1.1,
    targets: 'any',
    splash: false,
  },
};

const DECK = ['knight', 'archer', 'giant', 'goblin', 'wizard', 'dragon', 'golem', 'musketeer'];
